/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareerAgentRouteImport } from './routes/career-agent'
import { Route as CareerGoalRouteImport } from './routes/career-goal'
import { Route as CareerOpportunitiesRouteImport } from './routes/career-opportunities'
import { Route as CareerPlanRouteImport } from './routes/career-plan'
import { Route as CareerRoadmapRouteImport } from './routes/career-roadmap'
import { Route as CareerSimulatorRouteImport } from './routes/career-simulator'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PassportTokenRouteImport } from './routes/passport.$token'
import { Route as StudentCareerRouteImport } from './routes/student.career'
import { Route as StudentCareerCoachRouteImport } from './routes/student.career-coach'
import { Route as StudentEvolutionRouteImport } from './routes/student.evolution'
import { Route as StudentProjectsRouteImport } from './routes/student.projects'
import { Route as StudentSkillGraphRouteImport } from './routes/student.skill-graph'
import { Route as StudentSkillVerificationRouteImport } from './routes/student.skill-verification'
import { Route as StudentSkillsRouteImport } from './routes/student.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAgentRoute = CareerAgentRouteImport.update({
  id: '/career-agent',
  path: '/career-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGoalRoute = CareerGoalRouteImport.update({
  id: '/career-goal',
  path: '/career-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerOpportunitiesRoute = CareerOpportunitiesRouteImport.update({
  id: '/career-opportunities',
  path: '/career-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPlanRoute = CareerPlanRouteImport.update({
  id: '/career-plan',
  path: '/career-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoadmapRoute = CareerRoadmapRouteImport.update({
  id: '/career-roadmap',
  path: '/career-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSimulatorRoute = CareerSimulatorRouteImport.update({
  id: '/career-simulator',
  path: '/career-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportTokenRoute = PassportTokenRouteImport.update({
  id: '/passport/$token',
  path: '/passport/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCareerRoute = StudentCareerRouteImport.update({
  id: '/student/career',
  path: '/student/career',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCareerCoachRoute = StudentCareerCoachRouteImport.update({
  id: '/student/career-coach',
  path: '/student/career-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEvolutionRoute = StudentEvolutionRouteImport.update({
  id: '/student/evolution',
  path: '/student/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProjectsRoute = StudentProjectsRouteImport.update({
  id: '/student/projects',
  path: '/student/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSkillGraphRoute = StudentSkillGraphRouteImport.update({
  id: '/student/skill-graph',
  path: '/student/skill-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSkillVerificationRoute =
  StudentSkillVerificationRouteImport.update({
    id: '/student/skill-verification',
    path: '/student/skill-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentSkillsRoute = StudentSkillsRouteImport.update({
  id: '/student/skills',
  path: '/student/skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career-agent': typeof CareerAgentRoute
  '/career-goal': typeof CareerGoalRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/career-plan': typeof CareerPlanRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/college': typeof CollegeRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/recruiter': typeof RecruiterRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/career': typeof StudentCareerRoute
  '/student/career-coach': typeof StudentCareerCoachRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/skill-graph': typeof StudentSkillGraphRoute
  '/student/skill-verification': typeof StudentSkillVerificationRoute
  '/student/skills': typeof StudentSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career-agent': typeof CareerAgentRoute
  '/career-goal': typeof CareerGoalRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/career-plan': typeof CareerPlanRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/college': typeof CollegeRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/recruiter': typeof RecruiterRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/career': typeof StudentCareerRoute
  '/student/career-coach': typeof StudentCareerCoachRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/skill-graph': typeof StudentSkillGraphRoute
  '/student/skill-verification': typeof StudentSkillVerificationRoute
  '/student/skills': typeof StudentSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career-agent': typeof CareerAgentRoute
  '/career-goal': typeof CareerGoalRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/career-plan': typeof CareerPlanRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/career-simulator': typeof CareerSimulatorRoute
  '/college': typeof CollegeRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/learning': typeof LearningRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/recruiter': typeof RecruiterRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/passport/$token': typeof PassportTokenRoute
  '/student/career': typeof StudentCareerRoute
  '/student/career-coach': typeof StudentCareerCoachRoute
  '/student/evolution': typeof StudentEvolutionRoute
  '/student/projects': typeof StudentProjectsRoute
  '/student/skill-graph': typeof StudentSkillGraphRoute
  '/student/skill-verification': typeof StudentSkillVerificationRoute
  '/student/skills': typeof StudentSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/career-agent'
    | '/career-goal'
    | '/career-opportunities'
    | '/career-plan'
    | '/career-roadmap'
    | '/career-simulator'
    | '/college'
    | '/company'
    | '/dashboard'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/recruiter'
    | '/register'
    | '/settings'
    | '/passport/$token'
    | '/student/career'
    | '/student/career-coach'
    | '/student/evolution'
    | '/student/projects'
    | '/student/skill-graph'
    | '/student/skill-verification'
    | '/student/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/career-agent'
    | '/career-goal'
    | '/career-opportunities'
    | '/career-plan'
    | '/career-roadmap'
    | '/career-simulator'
    | '/college'
    | '/company'
    | '/dashboard'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/recruiter'
    | '/register'
    | '/settings'
    | '/passport/$token'
    | '/student/career'
    | '/student/career-coach'
    | '/student/evolution'
    | '/student/projects'
    | '/student/skill-graph'
    | '/student/skill-verification'
    | '/student/skills'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/career-agent'
    | '/career-goal'
    | '/career-opportunities'
    | '/career-plan'
    | '/career-roadmap'
    | '/career-simulator'
    | '/college'
    | '/company'
    | '/dashboard'
    | '/jobs'
    | '/learning'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/recruiter'
    | '/register'
    | '/settings'
    | '/passport/$token'
    | '/student/career'
    | '/student/career-coach'
    | '/student/evolution'
    | '/student/projects'
    | '/student/skill-graph'
    | '/student/skill-verification'
    | '/student/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareerAgentRoute: typeof CareerAgentRoute
  CareerGoalRoute: typeof CareerGoalRoute
  CareerOpportunitiesRoute: typeof CareerOpportunitiesRoute
  CareerPlanRoute: typeof CareerPlanRoute
  CareerRoadmapRoute: typeof CareerRoadmapRoute
  CareerSimulatorRoute: typeof CareerSimulatorRoute
  CollegeRoute: typeof CollegeRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LearningRoute: typeof LearningRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  RecruiterRoute: typeof RecruiterRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  PassportTokenRoute: typeof PassportTokenRoute
  StudentCareerRoute: typeof StudentCareerRoute
  StudentCareerCoachRoute: typeof StudentCareerCoachRoute
  StudentEvolutionRoute: typeof StudentEvolutionRoute
  StudentProjectsRoute: typeof StudentProjectsRoute
  StudentSkillGraphRoute: typeof StudentSkillGraphRoute
  StudentSkillVerificationRoute: typeof StudentSkillVerificationRoute
  StudentSkillsRoute: typeof StudentSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-agent': {
      id: '/career-agent'
      path: '/career-agent'
      fullPath: '/career-agent'
      preLoaderRoute: typeof CareerAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-goal': {
      id: '/career-goal'
      path: '/career-goal'
      fullPath: '/career-goal'
      preLoaderRoute: typeof CareerGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-opportunities': {
      id: '/career-opportunities'
      path: '/career-opportunities'
      fullPath: '/career-opportunities'
      preLoaderRoute: typeof CareerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-plan': {
      id: '/career-plan'
      path: '/career-plan'
      fullPath: '/career-plan'
      preLoaderRoute: typeof CareerPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-roadmap': {
      id: '/career-roadmap'
      path: '/career-roadmap'
      fullPath: '/career-roadmap'
      preLoaderRoute: typeof CareerRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-simulator': {
      id: '/career-simulator'
      path: '/career-simulator'
      fullPath: '/career-simulator'
      preLoaderRoute: typeof CareerSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$token': {
      id: '/passport/$token'
      path: '/passport/$token'
      fullPath: '/passport/$token'
      preLoaderRoute: typeof PassportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/career': {
      id: '/student/career'
      path: '/student/career'
      fullPath: '/student/career'
      preLoaderRoute: typeof StudentCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/career-coach': {
      id: '/student/career-coach'
      path: '/student/career-coach'
      fullPath: '/student/career-coach'
      preLoaderRoute: typeof StudentCareerCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/evolution': {
      id: '/student/evolution'
      path: '/student/evolution'
      fullPath: '/student/evolution'
      preLoaderRoute: typeof StudentEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/projects': {
      id: '/student/projects'
      path: '/student/projects'
      fullPath: '/student/projects'
      preLoaderRoute: typeof StudentProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skill-graph': {
      id: '/student/skill-graph'
      path: '/student/skill-graph'
      fullPath: '/student/skill-graph'
      preLoaderRoute: typeof StudentSkillGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skill-verification': {
      id: '/student/skill-verification'
      path: '/student/skill-verification'
      fullPath: '/student/skill-verification'
      preLoaderRoute: typeof StudentSkillVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/skills': {
      id: '/student/skills'
      path: '/student/skills'
      fullPath: '/student/skills'
      preLoaderRoute: typeof StudentSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareerAgentRoute: CareerAgentRoute,
  CareerGoalRoute: CareerGoalRoute,
  CareerOpportunitiesRoute: CareerOpportunitiesRoute,
  CareerPlanRoute: CareerPlanRoute,
  CareerRoadmapRoute: CareerRoadmapRoute,
  CareerSimulatorRoute: CareerSimulatorRoute,
  CollegeRoute: CollegeRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LearningRoute: LearningRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  RecruiterRoute: RecruiterRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  PassportTokenRoute: PassportTokenRoute,
  StudentCareerRoute: StudentCareerRoute,
  StudentCareerCoachRoute: StudentCareerCoachRoute,
  StudentEvolutionRoute: StudentEvolutionRoute,
  StudentProjectsRoute: StudentProjectsRoute,
  StudentSkillGraphRoute: StudentSkillGraphRoute,
  StudentSkillVerificationRoute: StudentSkillVerificationRoute,
  StudentSkillsRoute: StudentSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
